project:
  type: website
  output-dir: docs

website:
  title: "Zeynep TUNCABOYLU's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd
      - text: My Posts
        href: posts.qmd
      - text: "Data Analytics Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://emu-hacettepe-analytics.github.io/emu430-fall2023-zeyneptnc/
      - icon: linkedin
        href: https://www.linkedin.com/in/zeynep-t-57b789232
  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/Introduction to R Assignment.qmd
        - assignments/Web Scraping (Imdb Ratings) Assignment.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe - IE" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: united
      dark:  united
    css: styles.css

editor: visual

